--Author:Luis Diaz
--Contacto: 8127278053
--99diazluisfernand@gmail.com
--

CREATE TABLE process_receipts.receipts(
    id_receipt UUID PRIMARY KEY,
    client INT NOT NULL, --DESPUES LLEVARA UNA REFERENCE
    name VARCHAR(200)  NOT NULL,
    extension VARCHAR(8),
    route VARCHAR(200)  NOT NULL,
    size BIGINT  NOT NULL, --bytes
    arrival_date DATE NOT NULL,
    width INT NOT NULL,
    height INT NOT NULL
);


CREATE TABLE process_receipts.receipts_process (
    id_receipt_process BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_receipt UUID NOT NULL REFERENCES process_receipts.receipts(id_receipt) UNIQUE,
    bank VARCHAR(10),
    version_bank VARCHAR(200),
    mount_process NUMERIC(10,2),
    route_process VARCHAR(500)
);

--drop table process_receipts.receipts_process;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";




