--Author:Luis Diaz
--Contacto: 8127278053
--99diazluisfernand@gmail.com
--

CREATE TABLE business_receipts.clients(
    id_client UUID PRIMARY KEY,
    name_client VARCHAR(40) NOT NULL,
    active boolean NOT NULL,
    create_date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE business_receipts.transactions(
    id_transaction BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_client UUID NOT NULL REFERENCES business_receipts.clients(id_client),
    id_receipt_process NULL BIGINT,
    date_transaction TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    code VARCHAR(2) NULL --00 correcto, 02 respuesta incorrecta
);

CREATE TABLE business_receipts.clients_coins(
    id_client UUID NOT NULL REFERENCES business_receipts.clients(id_client) UNIQUE,
    coins_available INT NOT NULL,
    coins_spent INT NOT NULL,
    last_recharge TIMESTAMPTZ NULL
)